### ISSUE TITLE
Ошибка sharepath is null

### ISSUE THREAD

**Issue by coraxkrsk** [PilotTeam/PilotRevitIntegrator#12]
Добрый день,
Установил и настроил расширение согласно инструкции. 
Версия: Revit 2019.1
Pilot-ICE 20.8.0.33198
Утилита rsladmin показывает:
Revit shared folder path: e:\revitshare
delay: 30000 mls
license code is 100
connected to http://oa:5545/DNStest

Т.е. расшаренная папка локальная на данном ПК.
При запуске команды в Revit - Pilot-ICE - Подготовить проект, указываю папку на Storage для сохранения модели. В Pilot появляется маленькое окно с ошибкой Share path is null.  результате Revit висит, на Storage появляется файл модели rvt размером 0 байт. С чем может быть связана ошибка?
![Подключение](https://user-images.githubusercontent.com/65324776/81888564-ce48d200-95cb-11ea-8d5d-3948da742d98.png)

**Comment by coraxkrsk** [comment]
Log для данных действий следующий:

14-05-2020 10:27:47  INFO [156] Notify on file e:\revitshare\Проект1.rvt 
14-05-2020 10:27:47  INFO [156] Stream is null e:\revitshare\Проект1.rvt 
14-05-2020 10:28:14  INFO [139] Notify on file e:\revitshare\Проект1.rvt 
14-05-2020 10:28:14 ERROR [139] Файл 'e:\revitshare\Проект1.rvt.ini' не найден. 
14-05-2020 10:28:15  INFO [139] Notify on file e:\revitshare\Проект1.rvt 
14-05-2020 10:28:15 ERROR [139] Файл 'e:\revitshare\Проект1.rvt.ini' не найден. 
14-05-2020 10:28:15  INFO [139] Notify on file e:\revitshare\Проект1.rvt 
14-05-2020 10:28:15 ERROR [139] Файл 'e:\revitshare\Проект1.rvt.ini' не найден. 
14-05-2020 10:28:15  INFO [139] Notify on file e:\revitshare\Проект1.rvt 
14-05-2020 10:28:15 ERROR [139] Файл 'e:\revitshare\Проект1.rvt.ini' не найден. 
14-05-2020 10:28:15  INFO [139] Notify on file e:\revitshare\Проект1.rvt 
14-05-2020 10:28:15 ERROR [139] Файл 'e:\revitshare\Проект1.rvt.ini' не найден. 
14-05-2020 10:28:15  INFO [139] Notify on file e:\revitshare\Проект1.rvt 
14-05-2020 10:28:15 ERROR [139] Файл 'e:\revitshare\Проект1.rvt.ini' не найден. 
14-05-2020 10:28:16  INFO [139] Notify on file e:\revitshare\Проект1.rvt 
14-05-2020 10:28:16 ERROR [139] Файл 'e:\revitshare\Проект1.rvt.ini' не найден. 
14-05-2020 10:28:16  INFO [139] Notify on file e:\revitshare\Проект1.rvt 
14-05-2020 10:28:16 ERROR [139] Файл 'e:\revitshare\Проект1.rvt.ini' не найден. 
14-05-2020 10:28:16  INFO [139] Notify on file e:\revitshare\Проект1.rvt 
14-05-2020 10:28:16 ERROR [139] Файл 'e:\revitshare\Проект1.rvt.ini' не найден. 
14-05-2020 10:28:16  INFO [139] Notify on file e:\revitshare\Проект1.rvt 
14-05-2020 10:28:16 ERROR [139] Файл 'e:\revitshare\Проект1.rvt.ini' не найден. 
14-05-2020 10:28:16  INFO [139] Notify on file e:\revitshare\Проект1.rvt 
14-05-2020 10:28:16 ERROR [139] Файл 'e:\revitshare\Проект1.rvt.ini' не найден. 
14-05-2020 10:28:17  INFO [139] Notify on file e:\revitshare\Проект1.rvt 
14-05-2020 10:28:17 ERROR [139] Файл 'e:\revitshare\Проект1.rvt.ini' не найден. 
14-05-2020 10:28:17  INFO [139] Notify on file e:\revitshare\Проект1.rvt 
14-05-2020 10:28:17  INFO [139] Stream is null e:\revitshare\Проект1.rvt 
14-05-2020 10:28:47  INFO [156] Notify on file e:\revitshare\Проект1.rvt 
14-05-2020 10:28:47  INFO [156] Stream is null e:\revitshare\Проект1.rvt 
14-05-2020 10:29:17  INFO [139] Notify on file e:\revitshare\Проект1.rvt 
14-05-2020 10:29:17  INFO [139] Stream is null e:\revitshare\Проект1.rvt 
14-05-2020 10:29:47  INFO [156] Notify on file e:\revitshare\Проект1.rvt 
14-05-2020 10:29:47  INFO [156] Stream is null e:\revitshare\Проект1.rvt 

Соответственно Revit весит пытаясь выполнить операции и лог продолжает пополняться строками:
14-05-2020 10:28:17  INFO [139] Notify on file e:\revitshare\Проект1.rvt 
14-05-2020 10:28:17  INFO [139] Stream is null e:\revitshare\Проект1.rvt 
14-05-2020 10:28:47  INFO [156] Notify on file e:\revitshare\Проект1.rvt 
14-05-2020 10:28:47  INFO [156] Stream is null e:\revitshare\Проект1.rvt

**Comment by Olkhovsky** [comment]
Добрый день! Вам нужно в общих настройках клиента указать директорию расширенной папки 
![изображение](https://user-images.githubusercontent.com/53400370/82470627-42084480-9ace-11ea-886b-8822eff8cc34.png)
Более подробно в п.2. Установка в базу Pilot-ICE модуля PilotRevitAgregator
https://github.com/PilotTeam/PilotRevitIntegrator
