### ISSUE TITLE
Revit2020

### ISSUE THREAD

**Issue by TimurRahmatullin** [PilotTeam/PilotRevitIntegrator#14]
Добрый день. Подскажите, пожалуйста, какая версия PilotRevitIntegrator совместима с Revit 2020?

**Comment by Olkhovsky** [comment]
Добрый день! Последняя версия PilotRevitIntegrator (20.05.25) совместима с Revit 2020.

**Comment by TimurRahmatullin** [comment]
добрый день. Спасибо за информвцию.

**Comment by TimurRahmatullin** [comment]
Спасибо
