### ISSUE TITLE
Отсутсвуют файлы в Ascon.Pilot.SDK.RevitShareAgregator

### ISSUE THREAD

**Issue by Graf-Hub** [PilotTeam/PilotRevitIntegrator#2]
Ascon.Pilot.SDK.RevitShareAgregator.zip отсутствует в папке. 
В  beta1 имеется. Работа ответственная хочется пользоваться стабильной версией, но не бетой.

**Comment by PilotTeam** [comment]
Файл "Ascon.Pilot.SDK.RevitShareAgregator.zip" находится в папке  "binaries17.5.23.0\Ascon.Pilot.SDK.RevitShareAgregator\"

Работа ответственная хочется пользоваться стабильной версией, но не бетой.
>
Эта версия имеет статус стабильной и в ближайшее время будет переведена в релиз без изменений.

**Comment by Graf-Hub** [comment]
В beta1 есть. А в стабильной версии? Которая в корне "<>Code".

**Comment by Graf-Hub** [comment]
Ясно. Ок. У меня Windows 10 синим экраном вылетела, сразу после установки расширения. Ни разу не вылетала до этого. Посмотрите, может где трабл.

**Comment by Graf-Hub** [comment]
Пункт 2.2
В меню СЕРВИС Pilot-ICE вызвать Настройки → Управление общими настройками → Revit project path for Agregator
В PILOT-ICE нет пункта "Настройки → Управление общими настройками" Эти настройки в PILOT-ICE Enterprise

**Comment by PilotTeam** [comment]
Парактически везде указан PILOT-ICE вместо PILOT-ICE Enterprise - вводит в заблуждение.
>
Модули работоспособны в том числе и для Pilot-ICE

**Comment by PilotTeam** [comment]
Ясно. Ок. У меня Windows 10 синим экраном вылетела, сразу после установки расширения. Ни разу не вылетала до этого. Посмотрите, может где трабл.
>
Пока не удалось воспроизвести BSOD, будем мониторить поведение.
