### ISSUE TITLE
Ошибка PilotRevitAddin

### ISSUE THREAD

**Issue by Erlenbah** [PilotTeam/PilotRevitIntegrator#4]
Приложению Ревит не удалось запустить команду внешнее приложение PilotRevitAddin
![default](https://user-images.githubusercontent.com/26789354/31117389-7c016054-a84b-11e7-8138-e81747f1301d.png)

**Comment by budaevb** [comment]
Проверьте отсутствие блокировки на загруженном zip-архиве (Свойства → Разблокировать).

**Comment by BontDimas** [comment]
Да, такая же проблемы была. Не понимаю зачем, разраб сделал zip архив заблокированным. Надо действительно нажать галочку Разблокировать архив binary, после чего рахархивировать. 
![Screenshot_198](https://user-images.githubusercontent.com/51233983/58709100-145c5400-83c2-11e9-82a4-7601b08c6ca4.png)
